version: "2.3"

services:
  test-2.5:
    build:
      context: .
      args:
        RUBY_VERSION: 2.5
    image: bbk-amqp-tests:2.5
    working_dir: /home/app
    
  test-3.2:
    build:
      context: .
      args:
        RUBY_VERSION: 3.2
    image: bbk-amqp-tests:3.2
    working_dir: /home/app
    